#스페이스 규칙
server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql:###/blog?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ###
    password: ###
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB